<?php

namespace App\Services\MikrotikSuite\Monitoring;

class NtpService
{
    /**
     * Generate NTP Config Script
     */
    public function generateScript(array $data)
    {
        $version = $data['version'] ?? 'v7';
        $enabled = isset($data['enabled']) ? filter_var($data['enabled'], FILTER_VALIDATE_BOOLEAN) : true;

        $primary = trim($data['primary'] ?? 'time.google.com');
        $secondary = trim($data['secondary'] ?? '');
        $servers = $data['servers'] ?? [];
        $mode = $data['mode'] ?? 'unicast';
        $interval = (int) ($data['interval'] ?? 5);
        $timezone = trim($data['timezone'] ?? '');
        $optManualTZ = filter_var($data['optManualTZ'] ?? false, FILTER_VALIDATE_BOOLEAN);
        $optDisableCloudUpdate = filter_var($data['optDisableCloudUpdate'] ?? false, FILTER_VALIDATE_BOOLEAN);
        $v7UseAddServers = filter_var($data['v7UseAddServers'] ?? false, FILTER_VALIDATE_BOOLEAN);

        $script = [];

        // Header
        $dateStr = date('d/m/Y H.i.s');
        $script[] = "# MikroTik NTP Client Configuration Generator";
        $script[] = "# Generated by Tajawaz solutions";
        $script[] = "# Date: {$dateStr}";
        $script[] = "# RouterOS: {$version}";
        $script[] = "";

        if ($version === 'v7') {
            $srv = $servers;
            if (!is_array($srv) || empty($srv))
                $srv = array_filter([$primary, $secondary]);
            // Clean and filter
            $srv = array_filter(array_map('trim', $srv), function ($server) {
                return $server !== '';
            });

            $script[] = "/system ntp client";
            $settings = "set enabled=" . ($enabled ? 'yes' : 'no');

            if ($enabled) {
                $settings .= " mode={$mode}";

                if (!$v7UseAddServers) {
                    $serverList = implode(',', $srv);
                    $settings .= " servers=\"{$serverList}\"";
                }
            }
            $script[] = $settings;

            if ($enabled && $v7UseAddServers && !empty($srv)) {
                $script[] = "";
                $script[] = "/system ntp client servers";
                $script[] = "remove [find]";
                foreach ($srv as $server) {
                    $script[] = "add address=\"{$server}\"";
                }
            }

        } else {
            // v6 Syntax
            $enabledStr = $enabled ? 'yes' : 'no';
            $primary = $primary ?: '0.0.0.0';
            $secondary = $secondary ?: '0.0.0.0';

            $script[] = "/system ntp client";
            $script[] = "set enabled={$enabledStr} mode={$mode} primary-ntp=\"{$primary}\" secondary-ntp=\"{$secondary}\"";

            // v6 does not use separate server list in basic client
            if (!empty($servers)) {
                // If there are extra servers, v6 usually only takes primary/secondary in standard client pkg
                // but we can add comment
                $script[] = "# Note: RouterOS v6 standard NTP client only supports Primary and Secondary.";
                $extra = array_diff($servers, [$primary, $secondary]);
                if (!empty($extra)) {
                    $script[] = "# Ignored extra servers: " . implode(', ', $extra);
                }
            }
        }

        // Timezone Logic
        $script[] = "";
        if ($optManualTZ && !empty($timezone)) {
            $script[] = "/system clock";
            $script[] = "set time-zone-name=\"{$timezone}\"";
            if ($optDisableCloudUpdate) {
                $script[] = "/ip cloud set update-time=no";
            }
        }

        // Add note about interval since NTP client settings differ widely across versions for interval
        // Some versions use 'poll-interval' (read-only usually) or 'min-poll'/'max-poll' in v7
        if ($version === 'v7') {
            // Assuming user wanted to set poll interval if possible, but v7 uses min-poll/max-poll
            // We'll skip complex interval logic to avoid errors unless specific command known
        }

        return implode("\n", $script);
    }

    /**
     * Test Connectivity of NTP Servers
     */
    public function testServers(array $servers)
    {
        $results = [];
        foreach ($servers as $server) {
            $server = trim($server);
            if (empty($server))
                continue;

            $res = [
                'server' => $server,
                'status' => 'unknown',
                'response_time' => null,
                'error' => null
            ];

            try {
                // Determine OS and ping
                $isWin = strtoupper(substr(PHP_OS, 0, 3)) === 'WIN';
                $pingCmd = $isWin ? "ping -n 1 -w 1500 " . escapeshellarg($server)
                    : "ping -c 1 -W 2 " . escapeshellarg($server);

                $output = [];
                $retVar = 0;
                @exec($pingCmd, $output, $retVar);

                if ($retVar === 0) {
                    $res['status'] = 'reachable';
                    // Parse time if possible, simplify for now
                    $time = 'N/A';
                    foreach ($output as $line) {
                        if (preg_match('/time[=<](\d+ms)/i', $line, $m)) {
                            $time = $m[1];
                            break;
                        }
                    }
                    $res['response_time'] = $time;
                } else {
                    $res['status'] = 'unreachable';
                    $res['error'] = 'Ping failed';
                }
            } catch (\Exception $e) {
                $res['status'] = 'error';
                $res['error'] = $e->getMessage();
            }
            $results[] = $res;
        }

        return [
            'success' => true,
            'results' => $results,
            'summary' => [
                'total' => count($results),
                'reachable' => count(array_filter($results, fn($r) => $r['status'] === 'reachable')),
                'unreachable' => count(array_filter($results, fn($r) => $r['status'] !== 'reachable')),
            ]
        ];
    }
}
