<?php

namespace App\Services\MikrotikSuite\Network;

class LoadBalanceService
{
    /**
     * Generate LB ECMP Script
     */
    public function generateEcmpScript(array $data)
    {
        if (!isset($data['wanData']) || !is_array($data['wanData'])) {
            throw new \Exception('Invalid input: wanData required');
        }

        $wanData = array_values(array_filter($data['wanData'], function ($wan) {
            return !empty(trim($wan['interface'] ?? '')) && !empty(trim($wan['gateway'] ?? ''));
        }));

        if (count($wanData) < 2) {
            throw new \Exception('Minimum 2 WAN connections required for ECMP');
        }

        $rosVersion = $data['rosVersion'] ?? 'RouterOS v6.xx';
        $recursiveGateway = filter_var($data['recursiveGateway'] ?? false, FILTER_VALIDATE_BOOLEAN);
        $bandwidthRatio = filter_var($data['bandwidthRatio'] ?? false, FILTER_VALIDATE_BOOLEAN);

        $script = [];
        $dateStr = date('d/m/Y H.i.s');

        $script[] = "# MikroTik Load Balancing ECMP (Equal Cost Multi-Path)";
        $script[] = "# Generated by Tajawaz solutions";
        $script[] = "# Date: {$dateStr}";
        $script[] = "# RouterOS: {$rosVersion}";
        $script[] = "# WAN ISPs: " . count($wanData);
        $script[] = "# Recursive Gateway: " . ($recursiveGateway ? 'on' : 'off');
        $script[] = "# Bandwidth Ratio: " . ($bandwidthRatio ? 'on' : 'off');
        $script[] = "";

        // NAT Rules
        $script[] = "# Rule: Configure NAT Masquerade for each WAN interface.";
        $script[] = "/ip firewall nat";
        foreach ($wanData as $index => $wan) {
            $interface = $wan['interface'];
            $ispNum = $index + 1;
            $script[] = "add chain=srcnat out-interface=\"{$interface}\" action=masquerade comment=\"Nat Masquerade to ISP-{$ispNum}\"";
        }
        $script[] = "";

        // Route Rules
        $script[] = "# Rule: Configure IP Routes.";
        $script[] = "/ip route";
        $script[] = "# Remove any existing default routes.";
        $script[] = "remove [find where dst-address=\"0.0.0.0/0\"]";
        $script[] = "";

        // Recursive Gateway Check Routes
        if ($recursiveGateway) {
            $script[] = "# Rule: Configure Recursive Gateway Check Routes.";
            foreach ($wanData as $index => $wan) {
                $gateway = $wan['gateway'];
                $dnsCheck = !empty($wan['dnsCheck']) ? $wan['dnsCheck'] : "1.1.1." . ($index + 1);
                $ispNum = $index + 1;

                if ($rosVersion === 'RouterOS v6.xx') {
                    $script[] = "add check-gateway=ping dst-address=\"{$dnsCheck}\" distance=1 gateway={$gateway} target-scope=\"10\" scope=\"10\" comment=\"ECMP Recursive Check ISP-{$ispNum}\"";
                } else {
                    // v7 often requires routing-table specification if not main, but standard ecmp usually is main
                    $script[] = "add check-gateway=ping dst-address=\"{$dnsCheck}\" distance=1 gateway={$gateway} routing-table=main target-scope=\"10\" scope=\"10\" comment=\"ECMP Recursive Check ISP-{$ispNum}\"";
                }
            }
            $script[] = "";
        }

        $script[] = "# Rule: Configure main ECMP default routes.";
        if ($rosVersion === 'RouterOS v6.xx') {
            if ($bandwidthRatio) {
                $script[] = "# Rule: Configure ECMP Default Route with bandwidth ratio.";
                $gwList = [];
                $commentParts = [];
                foreach ($wanData as $index => $wan) {
                    $gateway = $recursiveGateway ? ($wan['dnsCheck'] ?? "1.1.1." . ($index + 1)) : $wan['gateway'];
                    $ispSpeed = (int) ($wan['ispSpeed'] ?? 10);
                    $ispNum = $index + 1;
                    $gatewayCount = max(1, floor($ispSpeed / 50));

                    for ($i = 0; $i < $gatewayCount; $i++) {
                        $gwList[] = $gateway;
                    }
                    $commentParts[] = "ISP-{$ispNum} [{$gatewayCount}GW]";
                }
                $gwListStr = implode(',', $gwList);
                $comment = "ECMP Ratio : " . implode(', ', $commentParts);
                $script[] = "add dst-address=\"0.0.0.0/0\" check-gateway=ping distance=1 gateway=\"{$gwListStr}\" target-scope=\"30\" scope=\"30\" comment=\"{$comment}\"";
            } else {
                $script[] = "# Rule: Configure ECMP Default Route with multiple gateways in one line.";
                $gwList = [];
                foreach ($wanData as $index => $wan) {
                    $gwList[] = $recursiveGateway ? ($wan['dnsCheck'] ?? "1.1.1." . ($index + 1)) : $wan['gateway'];
                }
                $gwListStr = implode(',', $gwList);
                $script[] = "add dst-address=\"0.0.0.0/0\" check-gateway=ping distance=1 gateway=\"{$gwListStr}\" target-scope=\"30\" scope=\"30\" comment=\"ECMP Load Balance\"";
            }
        } else {
            // RouterOS v7 logic - v7 DOES NOT support comma separated gateways for ECMP same way, needs multiple routes with same distance/dst-address
            $script[] = "# Rule: Configure ECMP Default Routes for RouterOS v7.xx";
            foreach ($wanData as $index => $wan) {
                $gateway = $recursiveGateway ? ($wan['dnsCheck'] ?? "1.1.1." . ($index + 1)) : $wan['gateway'];
                $ispSpeed = (int) ($wan['ispSpeed'] ?? 10);
                $ispNum = $index + 1;

                $routeCount = $bandwidthRatio ? max(1, floor($ispSpeed / 50)) : 1;

                for ($i = 0; $i < $routeCount; $i++) {
                    // v7 ECMP is multiple routes
                    $script[] = "add dst-address=\"0.0.0.0/0\" check-gateway=ping distance=1 gateway={$gateway} routing-table=main target-scope=\"30\" scope=\"30\" comment=\"ECMP to ISP-{$ispNum}\"";
                }
            }
        }

        return implode("\n", $script);
    }
}
