<?php

declare(strict_types=1);

namespace App\Http\Controllers\MikrotikSuite\Connectivity;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;
use Illuminate\Contracts\View\View;

class VpnConfigurationController extends Controller
{
    /**
     * Display L2TP server configuration wizard
     */
    public function l2tpServer(): View
    {
        return view('mikrotik-suite.connectivity.vpn-configuration.l2tp-server');
    }

    /**
     * Display OpenVPN configuration wizard
     */
    public function openvpn(): View
    {
        return view('mikrotik-suite.connectivity.vpn-configuration.openvpn');
    }

    /**
     * Display PPTP server configuration wizard
     */
    public function pptpServer(): View
    {
        return view('mikrotik-suite.connectivity.vpn-configuration.pptp-server');
    }

    /**
     * Display SSTP server configuration wizard
     */
    public function sstpServer(): View
    {
        return view('mikrotik-suite.connectivity.vpn-configuration.sstp-server');
    }

    /**
     * Display VPN tunnel configuration wizard
     */
    public function vpnTunnel(): View
    {
        return view('mikrotik-suite.connectivity.vpn-configuration.vpn-tunnel');
    }

    /**
     * Display WireGuard configuration wizard
     */
    public function wireguard(): View
    {
        return view('mikrotik-suite.connectivity.vpn-configuration.wireguard');
    }

    // =========================================================================
    // GENERATION LOGIC
    // =========================================================================

    public function generateL2tpServer(Request $request): JsonResponse
    {
        $request->validate([
            'ipsec_secret' => 'required|string',
            'vpn_pool' => 'required|string',
            'local_address' => 'required|ipv4',
            'firewall' => 'boolean',
            'create_user' => 'boolean',
            'username' => 'nullable|string',
            'password' => 'nullable|string',
        ]);

        $secret = $request->input('ipsec_secret');
        $pool = $request->input('vpn_pool');
        $gateway = $request->input('local_address');
        $addFirewall = $request->boolean('firewall');
        $addUser = $request->boolean('create_user');

        $script = "# L2TP/IPsec Server Configuration\n";
        $script .= "# Generated by Dashboard Center\n\n";

        $script .= "# 1. IP Pool & Profile\n";
        $script .= "/ip pool add name=\"vpn-pool-l2tp\" ranges=\"{$pool}\"\n";
        $script .= "/ppp profile add name=\"profile-l2tp\" local-address=\"{$gateway}\" remote-address=\"vpn-pool-l2tp\" change-tcp-mss=yes dns-server=8.8.8.8,8.8.4.4\n\n";

        $script .= "# 2. Enable L2TP Server\n";
        $script .= "/interface l2tp-server server set enabled=yes use-ipsec=yes ipsec-secret=\"{$secret}\" default-profile=\"profile-l2tp\"\n\n";

        if ($addFirewall) {
            $script .= "# 3. Firewall Rules (Allow VPN Ports)\n";
            $script .= "/ip firewall filter\n";
            $script .= "add chain=input protocol=udp dst-port=500,1701,4500 action=accept comment=\"Allow L2TP/IPsec\"\n";
            $script .= "add chain=input protocol=ipsec-esp action=accept comment=\"Allow IPsec ESP\"\n\n";
        }

        if ($addUser) {
            $user = $request->input('username') ?: 'user1';
            $pass = $request->input('password') ?: 'password';
            $script .= "# 4. Create User\n";
            $script .= "/ppp secret add name=\"{$user}\" password=\"{$pass}\" service=l2tp profile=\"profile-l2tp\"\n";
        }

        return response()->json(['status' => 'success', 'script' => $script]);
    }

    public function generatePptpServer(Request $request): JsonResponse
    {
        $request->validate([
            'profile_name' => 'required|string',
            'local_address' => 'required|ipv4',
            'remote_address' => 'required|string',
            'auth_mschap2' => 'boolean',
            'auth_mschap1' => 'boolean',
            'auth_pap' => 'boolean',
        ]);

        $profile = $request->input('profile_name');
        $local = $request->input('local_address');
        $remote = $request->input('remote_address');
        $mschap2 = $request->boolean('auth_mschap2');
        $mschap1 = $request->boolean('auth_mschap1');
        $pap = $request->boolean('auth_pap');

        $auths = [];
        if ($mschap2)
            $auths[] = 'mschap2';
        if ($mschap1)
            $auths[] = 'mschap1';
        if ($pap)
            $auths[] = 'pap';

        if (empty($auths))
            $auths[] = 'mschap2';

        $authString = implode(',', $auths);

        $script = "/interface pptp-server server set enabled=yes authentication={$authString}\n";

        // Pool
        $poolName = "{$profile}-pool";
        $script .= "/ip pool add name=\"{$poolName}\" ranges={$remote}\n";

        // Profile
        $script .= "/ppp profile add name=\"{$profile}\" local-address={$local} remote-address=\"{$poolName}\" change-tcp-mss=yes\n";
        $script .= "/interface pptp-server server set default-profile=\"{$profile}\"\n";

        // Sample Secret
        $script .= "\n# Sample User (Secret)\n";
        $script .= "/ppp secret add name=\"user1\" password=\"UserPass123\" service=pptp profile=\"{$profile}\"\n";

        return response()->json(['status' => 'success', 'script' => $script]);
    }

    public function generateSstpServer(Request $request): JsonResponse
    {
        $request->validate([
            'profile_name' => 'required|string',
            'local_address' => 'required|ipv4',
            'remote_address' => 'required|string',
            'generate_cert' => 'boolean',
        ]);

        $profile = $request->input('profile_name');
        $local = $request->input('local_address');
        $remote = $request->input('remote_address');
        $genCert = $request->boolean('generate_cert');

        $script = "";

        if ($genCert) {
            $script .= "# Certificate Generation (Run this first, might take time)\n";
            $script .= "/certificate add name=sstp-ca common-name=sstp-ca key-usage=key-cert-sign,crl-sign\n";
            $script .= "/certificate sign sstp-ca\n";
            $script .= ":delay 5s\n";
            $script .= "/certificate add name=sstp-server common-name=sstp-server key-usage=digital-signature,key-encipherment,tls-server\n";
            $script .= "/certificate sign sstp-server ca=sstp-ca\n";
            $script .= ":delay 5s\n";
            $script .= "/certificate set sstp-server trusted=yes\n\n";
        }

        $script .= "# Configuration\n";
        // Pool
        $poolName = "{$profile}-pool";
        $script .= "/ip pool add name=\"{$poolName}\" ranges={$remote}\n";

        // Profile
        $script .= "/ppp profile add name=\"{$profile}\" local-address={$local} remote-address=\"{$poolName}\" change-tcp-mss=yes\n";

        // Interface
        $script .= "/interface sstp-server server set enabled=yes default-profile=\"{$profile}\" certificate=sstp-server authentication=mschap2\n";

        // Sample Secret
        $script .= "\n# Sample Secret\n";
        $script .= "/ppp secret add name=\"sstpuser\" password=\"SttpPassword!23\" service=sstp profile=\"{$profile}\"\n";

        return response()->json(['status' => 'success', 'script' => $script]);
    }
    public function generateOpenVpn(Request $request): JsonResponse
    {
        $request->validate([
            'profile_name' => 'required|string',
            'local_address' => 'required|ipv4',
            'remote_address' => 'required|string',
            'generate_cert' => 'boolean',
            'auth_alg' => 'required|string',
            'cipher_alg' => 'required|string',
        ]);

        $profile = $request->input('profile_name');
        $local = $request->input('local_address');
        $remote = $request->input('remote_address');
        $genCert = $request->boolean('generate_cert');
        $auth = $request->input('auth_alg');
        $cipher = $request->input('cipher_alg');

        $script = "";

        if ($genCert) {
            $script .= "# Certificate Generation (Automated CA & Server)\n";
            $script .= "/certificate add name=ovpn-ca common-name=ovpn-ca key-usage=key-cert-sign,crl-sign\n";
            $script .= "/certificate sign ovpn-ca\n";
            $script .= ":delay 5s\n";
            $script .= "/certificate add name=ovpn-server common-name=ovpn-server key-usage=digital-signature,key-encipherment,tls-server\n";
            $script .= "/certificate sign ovpn-server ca=ovpn-ca\n";
            $script .= ":delay 5s\n";
            $script .= "/certificate set ovpn-server trusted=yes\n\n";
        }

        $script .= "# Pool & Profile\n";
        $poolName = "{$profile}-pool";
        $script .= "/ip pool add name=\"{$poolName}\" ranges={$remote}\n";

        $script .= "/ppp profile add name=\"{$profile}\" local-address={$local} remote-address=\"{$poolName}\" change-tcp-mss=yes\n";

        $script .= "# Interface Setup\n";
        $script .= "/interface ovpn-server server set enabled=yes certificate=ovpn-server default-profile=\"{$profile}\" auth={$auth} cipher={$cipher} require-client-certificate=no\n";

        // Sample Secret
        $script .= "\n# Sample Secret\n";
        $script .= "/ppp secret add name=\"ovpnuser\" password=\"SecurePass!\" service=ovpn profile=\"{$profile}\"\n";

        return response()->json(['status' => 'success', 'script' => $script]);
    }

    public function generateVpnTunnel(Request $request): JsonResponse
    {
        $request->validate([
            'type' => 'required|in:gre,ipip,eoip',
            'interface_name' => 'required|string',
            'remote_address' => 'required|string', // Could be IP or DNS
            'local_address' => 'nullable|ipv4',
            'tunnel_id' => 'required_if:type,eoip|nullable|integer',
            'use_ipsec' => 'boolean',
            'ipsec_secret' => 'nullable|required_if:use_ipsec,true|string',
        ]);

        $type = $request->input('type');
        $name = $request->input('interface_name');
        $remote = $request->input('remote_address');
        $local = $request->input('local_address');
        $tid = $request->input('tunnel_id');
        $useIpsec = $request->boolean('use_ipsec');
        $secret = $request->input('ipsec_secret');

        $script = "# Tunnel Configuration\n";
        $script .= "/interface {$type} add name=\"{$name}\" remote-address={$remote}";

        if ($local) {
            $script .= " local-address={$local}";
        }
        if ($type === 'eoip' && $tid) {
            $script .= " tunnel-id={$tid}";
        }

        if ($useIpsec) {
            $script .= " ipsec-secret=\"{$secret}\" allow-fast-path=no";
        }

        $script .= " disabled=no";

        return response()->json(['status' => 'success', 'script' => $script]);
    }

    public function generateWireGuard(Request $request): JsonResponse
    {
        $request->validate([
            'listen_port' => 'required|integer',
            'interface_name' => 'required|string',
            'network_address' => 'required|string', // CIDR
            'peers' => 'array',
            'peers.*.name' => 'required|string',
            'peers.*.ip' => 'required|string',
            'peers.*.public_key' => 'nullable|string',
        ]);

        $port = $request->input('listen_port');
        $name = $request->input('interface_name');
        $network = $request->input('network_address');
        $peers = $request->input('peers', []);

        $script = "# WireGuard Server Config\n";

        $script .= "# 1. Interface\n";
        $script .= "/interface wireguard add name={$name} listen-port={$port} comment=\"WG Server\"\n";
        $script .= "/ip address add address={$network} interface={$name}\n\n";

        $script .= "# 2. Peers\n";

        foreach ($peers as $peer) {
            $clientName = $peer['name'];
            $clientIp = $peer['ip'];
            $pubKey = $peer['public_key'];

            $keyPart = $pubKey ? "public-key=\"{$pubKey}\"" : "public-key=\"REPLACE_WITH_CLIENT_PUBLIC_KEY\"";

            $script .= "/interface wireguard peers add interface={$name} allowed-address={$clientIp} {$keyPart} comment=\"{$clientName}\"\n";
        }

        $script .= "\n# 3. Firewall\n";
        $script .= "/ip firewall filter add chain=input protocol=udp dst-port={$port} action=accept comment=\"Allow WireGuard\"\n";

        return response()->json(['status' => 'success', 'script' => $script]);
    }
}

