document.addEventListener('DOMContentLoaded', function () {
    const form = document.getElementById('skinForm');
    const out = document.getElementById('skinCheck');

    form.addEventListener('submit', function (e) {
        e.preventDefault();

        const grp = document.getElementById('grpName').value;
        const checks = document.querySelectorAll('input[type="checkbox"]:checked');

        // This is a simplified JSON representation. WebFig skins are complex.
        // We will generate a JSON structure that represents the 'hide' logic.

        const rules = {};
        checks.forEach(c => {
            // In real WebFig JSON, it's hierarchical. We simulate top-level hiding.
            rules[`menu.${c.value}`] = false; // false usually means hidden in some conceptual parsers or just "disabled"
        });

        const skinObj = {
            "name": grp,
            "note": "Generated by Dashboard Tools",
            "rules": rules
        };

        out.innerText = JSON.stringify(skinObj, null, 4) + "\n\n// Note: This JSON is a structural example. \n// To apply, copy specific parts to your skin JSON file or construct the skin manually in WebFig and 'Export' it.";
    });

    window.copyText = function (id) {
        const text = document.getElementById(id).innerText;
        navigator.clipboard.writeText(text).then(() => alert('Copied!'));
    }
});
